backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
# when using the default proxy server port
local_backend:
  url: http://localhost:4000

media_folder: "assets/img"

collections:
  - name: authors
    label: Authors
    identifier_field: name
    files:
      - file: "_data/authors.yml"
        name: author
        label: author
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Twitter", name: "twitter", widget: "string"}

  - name: event # Used in routes, e.g., /admin/collections/event
    label: Event # Used in the UI
    folder: "_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "Event Start", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
